window.TRANSLATIONS = {
  ar: {
    appName: 'يزي عاد',
    tagline: 'ساوندبورد مقالب نظيف، سريع، ومليان روح تونسية وعربية',
    nav: {
      home: 'الرئيسية',
      categories: 'التصنيفات',
      prank: 'أوضاع المقالب',
      favorites: 'المفضلة',
      profile: 'الملف الشخصي'
    },
    common: {
      play: 'تشغيل',
      download: 'تحميل',
      favorite: 'مفضلة',
      unfavorite: 'إزالة',
      like: 'إعجاب',
      search: 'ابحث عن صوت أو تصنيف',
      downloadAll: 'تحميل كل الأصوات',
      language: 'اللغة',
      arabic: 'العربية',
      english: 'الإنجليزية',
      topSounds: 'الأصوات الأكثر انتشارًا',
      categories: 'المكتبة',
      prankModes: 'أوضاع المقالب',
      favorites: 'مفضلتي',
      profile: 'حسابي',
      community: 'المجتمع',
      miniGames: 'الألعاب الصغيرة',
      instantPlay: 'تشغيل فوري',
      offlineReady: 'جاهز للعمل بدون إنترنت بعد أول فتح',
      clear: 'مسح',
      close: 'إغلاق',
      save: 'حفظ',
      start: 'ابدأ',
      stop: 'إيقاف',
      tryNow: 'جرّب الآن',
      uploaded: 'تمت المحاكاة بنجاح',
      noResults: 'مفيش نتائج مطابقة',
      all: 'الكل',
      top: 'ترند',
      likes: 'إعجابات',
      views: 'تشغيلات'
    },
    home: {
      heroTitle: 'خلي الضحك يبدأ من أول ضغطة',
      heroText: 'تطبيق prank mobile-first بخفة تونسية، دعم عربي/إنجليزي كامل، وأصوات أصلية شغالة أوفلاين.',
      quickActions: 'وصول سريع',
      exploreSounds: 'استكشف الأصوات',
      prankModes: 'افتح أوضاع المقالب',
      favorites: 'راجع مفضلتك',
      uploadTitle: 'واجهة رفع المجتمع',
      uploadText: 'شارك اسم الصوت والوصف والتصنيف. الرفع هنا تجريبي ومحاكى للحفاظ على العمل أوفلاين.',
      uploadButton: 'رفع تجريبي',
      topIntro: 'أصوات نظيفة ومضحكة سريعة الانتشار وقابلة للتحميل فورًا.',
      statsSounds: 'صوت',
      statsPranks: 'وضع مقلب',
      statsOffline: 'أوفلاين',
      topPranks: 'أقوى المقالب السريعة',
      languageHint: 'بدّل اللغة من الزر العلوي في أي وقت.'
    },
    categories: {
      title: 'كل التصنيفات',
      subtitle: 'من أصوات واقعية إلى ميمز نظيفة وزغاريد ورنات كلاسيكية.',
      realistic: 'أصوات واقعية',
      tunisian: 'ميمز تونسية نظيفة',
      arabic: 'ميمز عربية نظيفة',
      zaghrouda: 'زغرودة العالم',
      situational: 'أصوات مواقف',
      retro: 'رنات قديمة'
    },
    prank: {
      title: 'أوضاع المقالب',
      subtitle: 'تجارب تفاعلية سريعة تحوّل أي جلسة لجو مرح.',
      haircut: 'محاكي الحلاقة',
      haircutText: 'شغّل ماكينة وهمية واضبط السرعة وخلي أصحابك يلفوا وراهم.',
      fakeCall: 'مكالمة وهمية',
      fakeCallText: 'اعرض مكالمة داخلة باسم تختاره مع رنة قديمة ولمسة درامية.',
      ghost: 'وضع الشبح',
      ghostText: 'إظلام خفيف ورسائل مرعبة مؤدبة وصوت غامض.',
      panic: 'وضع الطوارئ',
      panicText: 'سيرين + بطارية منخفضة + اهتزاز سريع في ضغطة واحدة.',
      party: 'وضع الحفلة',
      partyText: 'نبضات نيون وزغاريد وبهجة فورية.',
      callerName: 'اسم المتصل',
      defaultCaller: 'المتصل الغامض',
      incomingCall: 'مكالمة واردة',
      answer: 'رد',
      decline: 'رفض',
      connected: 'تم الرد',
      ghostActive: 'الوضع الشبح اتفعل',
      panicActive: 'استعد... وضع الطوارئ شغّال',
      partyActive: 'الحفلة بدأت',
      simulatorSpeed: 'سرعة الماكينة',
      startHaircut: 'تشغيل الماكينة',
      stopHaircut: 'إيقاف الماكينة'
    },
    favorites: {
      title: 'المفضلة',
      subtitle: 'كل الأصوات اللي حفظتها محليًا على جهازك.',
      empty: 'لسه ما حفظتش أي صوت في المفضلة.'
    },
    profile: {
      title: 'الملف الشخصي',
      subtitle: 'إعدادات محلية وتجربة مستخدم أوفلاين بالكامل.',
      statsTitle: 'إحصائياتك',
      soundsUsed: 'أصوات متاحة',
      favCount: 'عدد المفضلة',
      likesGiven: 'إعجاباتك',
      offlineMode: 'الحالة',
      resetFavorites: 'تصفير المفضلة',
      resetLikes: 'تصفير الإعجابات',
      storage: 'يتم حفظ اللغة والمفضلة والإعجابات في localStorage.',
      deploy: 'جاهز للنشر على Netlify أو GitHub Pages.'
    },
    games: {
      reaction: 'لعبة سرعة الرد',
      reactionText: 'اضغط ابدأ ثم المس الزر فور تغيّر اللون.',
      wait: 'استنى الإشارة',
      tapNow: 'اضغط الآن',
      tooSoon: 'بدري جدًا',
      bestScore: 'أفضل زمن',
      laugh: 'تحدي لا تضحك',
      laughText: 'اسمع نكتة نظيفة أو جملة ميم، وإذا صمدت 10 ثواني تكسب نقطة.',
      challenge: 'ابدأ التحدي',
      survived: 'صمدت',
      score: 'النقاط',
      timer: 'الوقت'
    },
    toast: {
      addedFav: 'تمت الإضافة إلى المفضلة',
      removedFav: 'تمت الإزالة من المفضلة',
      downloaded: 'بدأ تحميل الصوت',
      downloadingAll: 'جاري تحميل كل الأصوات',
      uploadDone: 'تم إرسال الواجهة التجريبية',
      likesReset: 'تم تصفير الإعجابات',
      favoritesReset: 'تم تصفير المفضلة',
      languageSwitched: 'تم تغيير اللغة'
    },
    ghosts: ['في حد وراك؟', 'النور كان مطفي من شوية؟', 'الصوت ده جاي منين؟', 'إهدى... ده مجرد مقلب.'],
    jokes: ['يزي عاد، القعدة مش ناقصة ماكينة حلاقة!', 'مين شغّل الزغرودة في وسط المكتب؟', 'لما البطارية تقولك باي باي في أهم لحظة.', 'الصوت ده بريء... بس النتائج مش دايمًا بريئة.']
  },
  en: {
    appName: 'Yezi 3ad',
    tagline: 'A clean prank soundboard with Tunisian and Arabic flavor',
    nav: {
      home: 'Home',
      categories: 'Categories',
      prank: 'Prank Modes',
      favorites: 'Favorites',
      profile: 'Profile'
    },
    common: {
      play: 'Play',
      download: 'Download',
      favorite: 'Favorite',
      unfavorite: 'Remove',
      like: 'Like',
      search: 'Search sounds or categories',
      downloadAll: 'Download all sounds',
      language: 'Language',
      arabic: 'Arabic',
      english: 'English',
      topSounds: 'Top sounds',
      categories: 'Library',
      prankModes: 'Prank modes',
      favorites: 'Favorites',
      profile: 'Profile',
      community: 'Community',
      miniGames: 'Mini games',
      instantPlay: 'Instant play',
      offlineReady: 'Offline ready after first load',
      clear: 'Clear',
      close: 'Close',
      save: 'Save',
      start: 'Start',
      stop: 'Stop',
      tryNow: 'Try now',
      uploaded: 'Simulation completed',
      noResults: 'No matching results',
      all: 'All',
      top: 'Trending',
      likes: 'Likes',
      views: 'Plays'
    },
    home: {
      heroTitle: 'Start the laughter in one tap',
      heroText: 'A mobile-first prank app with Tunisian identity, full Arabic/English support, and original offline-ready sounds.',
      quickActions: 'Quick access',
      exploreSounds: 'Explore sounds',
      prankModes: 'Open prank modes',
      favorites: 'Open favorites',
      uploadTitle: 'Community upload UI',
      uploadText: 'Share a sound title, description, and category. Upload is simulated to keep the app fully offline.',
      uploadButton: 'Simulate upload',
      topIntro: 'Clean, funny, fast-to-share sounds with instant downloads.',
      statsSounds: 'sounds',
      statsPranks: 'prank modes',
      statsOffline: 'offline',
      topPranks: 'Fast viral prank picks',
      languageHint: 'Switch language anytime from the top button.'
    },
    categories: {
      title: 'All categories',
      subtitle: 'From realistic sound effects to clean memes, zaghrouda packs, and retro tones.',
      realistic: 'Realistic sounds',
      tunisian: 'Clean Tunisian memes',
      arabic: 'Clean Arabic memes',
      zaghrouda: 'Zaghrouda world',
      situational: 'Situational sounds',
      retro: 'Old phone ringtones'
    },
    prank: {
      title: 'Prank modes',
      subtitle: 'Quick interactive experiences that turn any hangout into a playful moment.',
      haircut: 'Haircut simulator',
      haircutText: 'Start a fake clipper and adjust speed for a classic barber prank.',
      fakeCall: 'Fake call',
      fakeCallText: 'Show an incoming call with a custom caller name and a retro ringtone.',
      ghost: 'Ghost mode',
      ghostText: 'Soft darkness, spooky polite messages, and a mysterious sound.',
      panic: 'Panic mode',
      panicText: 'Siren + low battery + vibration in one dramatic tap.',
      party: 'Party mode',
      partyText: 'Neon pulse, zaghrouda, and instant celebration energy.',
      callerName: 'Caller name',
      defaultCaller: 'Mystery caller',
      incomingCall: 'Incoming call',
      answer: 'Answer',
      decline: 'Decline',
      connected: 'Connected',
      ghostActive: 'Ghost mode activated',
      panicActive: 'Brace yourself... panic mode is on',
      partyActive: 'Party mode is live',
      simulatorSpeed: 'Clipper speed',
      startHaircut: 'Start clipper',
      stopHaircut: 'Stop clipper'
    },
    favorites: {
      title: 'Favorites',
      subtitle: 'All sounds saved locally on your device.',
      empty: 'You have not added any favorites yet.'
    },
    profile: {
      title: 'Profile',
      subtitle: 'Local settings and a fully offline-friendly user experience.',
      statsTitle: 'Your stats',
      soundsUsed: 'Available sounds',
      favCount: 'Favorites count',
      likesGiven: 'Your likes',
      offlineMode: 'Status',
      resetFavorites: 'Reset favorites',
      resetLikes: 'Reset likes',
      storage: 'Language, favorites, and likes are stored in localStorage.',
      deploy: 'Ready to deploy on Netlify or GitHub Pages.'
    },
    games: {
      reaction: 'Reaction game',
      reactionText: 'Tap start, then hit the button as soon as the color changes.',
      wait: 'Wait for the signal',
      tapNow: 'Tap now',
      tooSoon: 'Too early',
      bestScore: 'Best time',
      laugh: "Don't laugh challenge",
      laughText: 'Hear a clean meme line. If you survive 10 seconds, you earn a point.',
      challenge: 'Start challenge',
      survived: 'I survived',
      score: 'Score',
      timer: 'Timer'
    },
    toast: {
      addedFav: 'Added to favorites',
      removedFav: 'Removed from favorites',
      downloaded: 'Sound download started',
      downloadingAll: 'Downloading all sounds',
      uploadDone: 'Demo upload submitted',
      likesReset: 'Likes reset',
      favoritesReset: 'Favorites reset',
      languageSwitched: 'Language changed'
    },
    ghosts: ['Is someone behind you?', 'Was the light just off?', 'Where is that sound coming from?', 'Relax... it is only a prank.'],
    jokes: ['Yezi 3ad, the room does not need a fake haircut right now.', 'Who launched a zaghrouda in the middle of the office?', 'When the battery says goodbye at the worst possible time.', 'The sound is innocent... the reactions usually are not.']
  }
};
